#!/bin/sh

#chmod this file 755

if echo "$1" | grep -e jpg$ -e jpeg$ -e gif$ -e png$
then
  feh "$1"
else
        if echo "$1" | grep -e swf$ -e flv$
        then
        flashplayer "$1"
        else
chromium "$1"
fi
fi
